ci:
    skip: [pytest]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: check-yaml
-   repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
    -   id: toml-sort-fix
# -   repo: https://github.com/bwhmather/ssort
#     rev: v0.11.6
#     hooks:
#     -   id: ssort
#         exclude: __init__.py
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.290'
    hooks:
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
    -   id: mypy
        exclude: tests
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: conda
        pass_filenames: false
        always_run: true
fail_fast: true
