repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: tests
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [--line-length=88]
-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
    -   id: isort
        name: isort (python)
        args: [profile=black]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args: [--max-line-length=88, '--ignore=E203,W503,F401,F403']
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: conda
        pass_filenames: false
        always_run: true
fail_fast: true
