name: CI Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install ".[linters]"
    - name: Black code formatter
      run: black src --check
    - name: Isort sort imports
      run: isort src --check
    - name: Flake8 code checker
      run: flake8 src
    - name: Mypy code formatter
      run: mypy src
