name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        coverage: [false]
        include:
          - python-version: "3.14"
            coverage: true
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[tests]"
      - name: run pytest
        run: pytest --cov-report=lcov
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: "coverage.lcov"
        if: ${{ matrix.coverage }}
